# Generated by Django 4.1 on 2022-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecomolHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decomol', models.CharField(max_length=50)),
                ('data_liberacao', models.DateTimeField(auto_now_add=True)),
                ('resultado_cor', models.CharField(max_length=50)),
                ('sensorial', models.CharField(max_length=100)),
                ('brix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resultado_analise', models.BooleanField()),
            ],
        ),
    ]
