# Generated by Django 4.1 on 2022-09-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_trocahistorico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trocahistorico',
            old_name='decomol',
            new_name='decomol_troca',
        ),
    ]
