# Generated by Django 4.1 on 2022-09-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_rename_decomol_trocahistorico_decomol_troca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrocaHistorico',
        ),
    ]
