# Generated by Django 4.1 on 2022-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0004_delete_trocahistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decomolhistorico',
            name='data_liberacao',
            field=models.DateTimeField(blank=True),
        ),
    ]
