# Generated by Django 4.1 on 2022-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0006_alter_decomolhistorico_data_liberacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='decomolhistorico',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
