# Generated by Django 4.1 on 2022-11-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pulmao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanque', models.CharField(max_length=50)),
                ('data_analise', models.DateTimeField(auto_now=True)),
                ('resultado_cor', models.CharField(blank=True, max_length=50, null=True)),
                ('sensorial', models.CharField(blank=True, max_length=100, null=True)),
                ('brix', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
