# Generated by Django 4.1 on 2023-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oleo',
            name='data_analise',
            field=models.DateTimeField(),
        ),
    ]
