# Generated by Django 4.1 on 2023-07-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup', models.CharField(max_length=10)),
                ('parametro', models.CharField(max_length=50)),
                ('min_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unidade', models.CharField(max_length=10)),
            ],
        ),
    ]
