# Generated by Django 4.1 on 2022-08-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decomol',
            name='brix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='decomol',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='decomol',
            name='resultado_cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='decomol',
            name='sensorial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
