# Generated by Django 4.1 on 2022-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0002_alter_decomol_brix_alter_decomol_ph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decomol',
            name='em_analise',
            field=models.BooleanField(default=True),
        ),
    ]
