# Generated by Django 4.1 on 2022-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0003_decomol_em_analise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decomol',
            name='em_analise',
        ),
        migrations.AddField(
            model_name='decomol',
            name='troca_decomol',
            field=models.BooleanField(default=False),
        ),
    ]
