# Generated by Django 4.1 on 2022-10-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0004_remove_decomol_em_analise_decomol_troca_decomol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decomol',
            name='data_liberacao',
            field=models.DateTimeField(blank=True),
        ),
    ]
