# Generated by Django 4.1 on 2022-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0006_alter_decomol_data_liberacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decomol',
            name='data_liberacao',
            field=models.DateTimeField(null=True),
        ),
    ]
