# Generated by Django 4.1 on 2022-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0007_alter_decomol_data_liberacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decomol',
            name='data_liberacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
