# Generated by Django 4.1 on 2022-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0008_alter_decomol_data_liberacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decomol',
            name='troca_decomol',
        ),
        migrations.AddField(
            model_name='decomol',
            name='regenerando',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='decomol',
            name='liberado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
