# Generated by Django 4.1 on 2022-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0009_remove_decomol_troca_decomol_decomol_regenerando_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decomol',
            name='produzindo',
            field=models.BooleanField(default=False),
        ),
    ]
